# Generated by Django 5.0.4 on 2024-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=150)),
                ('gmail', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
